### ISSUE TITLE
Nemesis Matrices 4-piece (Global) - correction

### ISSUE THREAD

**Issue by Pyrosu** [whotookzakum/toweroffantasy.info#195]
Original: 
When healing yourself or your Electrode, the healed target gains a charge of "Lightning". The next attack within 30 seconds will cast lightning upon the target, dealing volt damage equal to 240%/300%/360%/420% of volt ATK, and damaeg caused by electrodes is reduced by 50%. Cannot be triggered more than once in 10 seconds. "Lightning" charges do not stack. Only the highest level's effect is applied when obtained repeatedly.

Correction:
When healing yourself or your Electrode, the healed target gains a charge of "Lightning". The next attack within 30 seconds will cast lightning upon the target, dealing volt damage equal to 240%/300%/360%/420% of volt ATK, and damage caused by electrodes is reduced by 50%. Cannot be triggered more than once in 10 seconds. "Lightning" charges do not stack. Only the highest level's effect is applied when obtained repeatedly.

**Comment by whotookzakum** [comment]
fixed now, changes will reflect in next update
