### ISSUE TITLE
Weapon mat upgrade costs (CN and Global)

### ISSUE THREAD

**Issue by whotookzakum** [whotookzakum/toweroffantasy.info#219]

**Comment by Pyrosu** [comment]
https://wiki.biligame.com/ht/%E6%AD%A6%E5%99%A8%E5%9B%BE%E9%89%B4
Click on Any weapon you want to check the value,
thereafter you press the blue link "more details" under the breakthrough mats that are listed there

**Comment by Pyrosu** [comment]
For global SSR weapons:
*2
*2
x3 x3
x3 x3 x3
x4 x4 x4
x6 x6 x6
x8 x8 x8
x11 x11 x11
x5 x5 x5

**Comment by Pyrosu** [comment]
x6 x6 x6

**Comment by whotookzakum** [comment]
lvl0 - lvl10 = 400g
lvl10 - lvl20 = 400g
lvl90 - lvl100 = 3600g
lvl100 - lvl 110 = 4000g

**Comment by whotookzakum** [comment]
leveling up = Enhance
break cap = Augment

**Comment by whotookzakum** [comment]
needs confirmation:
60-70: 3000
70-80: 4000
80-90: 5100 or 5200?

**Comment by whotookzakum** [comment]
**CHINA WEAPON UPGRADE REQUIREMENTS**
| Req. Wanderer Lv. | Wep. Level | Gold and EXP | Mats               |
| -------------------  | ------------------- | --------------- | --------------- |
|                               | 0-10                     | 700                 |                         |
| 10                          | raise cap to 20     | 400                 | x3                     |
|                               | 10-20                   | 1100               |                         |
| 15                          | raise cap to 30     | 800                 | x4                     |
|                               | 20-30                   | 1600               |                         |
| 20                          | raise cap to 40     | 1200               | x4 x4                |
|                               | 30-40                   | 2100               |                         |
| 25                          | raise cap to 50     | 1600               | x4 x4 x4           |
|                               | 40-50                   | 2800               |                         |
| 30                          | raise cap to 60     | 2000               | x6 x6 x6           |
|                               | 50-60                   | 3700               |                         |
| 35                          | raise cap to 70     | 2400               | x9 x9 x9           |
|                               | 60-70                   | 4900               |                         |
| 40                          | raise cap to 80     | 2800               | x13 x13 x13     |
|                               | 70-80                   | 6500               |                         |
| 45                          | raise cap to 90     | 3200               | x17 x17 x17     |
|                               | 80-90                   | 8000               |                         |
| 50                          | raise cap to 100   | 3600               | x7 x7 x7           |
|                               | 90-100                 | 11000             |                         |
| 55                          | raise cap to 110   | 4000               | x9 x9 x9           |
|                               | 100-110               | 12000             |                         |
| 60                          | raise cap to 120   | 4400               | x12 x12 x12     |
|                               | 110-120               | 12500             |                         |
| 65                          | raise cap to 130   | 4800               | x17 x17 x17     |
|                               | 120-130               | 13000             |                         |
| 70                          | raise cap to 140   | 5200               | x23 x23 x23     |
|                               | 130-140               | 13700             |                         |
| 75                          | raise cap to 150   | 5600               | x30 x30 x30     |
|                               | 140-150               | 14400             |                         |
| 80                          | raise cap to 160   | 6000               | x7 x7 x7           |
|                               | 150-160               | 15300             |                         |
| 80                          | raise cap to 170   | 6400               | x7 x7 x7           |
|                               | 160-170               | 16300             |                         |
| 80                          | raise cap to 180   | 6800               | x8 x8 x8           |
|                               | 170-180               | 17400             |                         |
| 80                          | raise cap to 190   | 7200               | x8 x8 x8           |
|                               | 180-190               | 18700             |                         |
| 80                          | raise cap to 200   | 7600               | x9 x9 x9           |
|                               | 190-200               | 20000             |                         |
